version: '3.8'
services:

  # CONFIG SERVER
  configsvr:
    image: mongo:latest
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - ./data/configdb:/data/db

  # SHARD 1
  shard1:
    image: mongo:latest
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - ./data/shard1:/data/db

  # SHARD 2
  shard2:
    image: mongo:latest
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27020"]
    ports:
      - "27020:27020"
    volumes:
      - ./data/shard2:/data/db

  # MONGOS ROUTER
  mongos:
    image: mongo:latest
    container_name: mongos
    depends_on:
      - configsvr
      - shard1
      - shard2
    command: >
      bash -c "
        sleep 10 &&
        mongos --configdb configReplSet/configsvr:27019 --port 27017 --bind_ip_all
      "
    ports:
      - "27017:27017"
